version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8002:8001
    volumes:
    - ./:/usr/src/app:ro
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=docker
      - DATABASE_PASSWORD=docker
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
  postgres:
    image: postgres
    environment: 
        - POSTGRES_PASSWORD=docker123
        - POSTGRES_DB=fastapi
    volumes:
        - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db: