version: "3"
services:
  api:
    image: sachinhr/fastapi
    depends_on:
      - postgres
    ports:
      - 8002:8001
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
  postgres:
    image: postgres
    environment: 
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}123
        - POSTGRES_DB=${DATABASE_NAME}
    volumes:
        - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db: